language: node_js
node_js: node
branches:
  only:
  - master
# addons:
#   ssh_known_hosts:
#   - gz.oidiotlin.com
install:
- npm install npm -g
- npm install --registry=https://registry.npm.taobao.org
- npm install pm2@latest -g
script:
- npm run prd
# after_success:
# - cd ./dist
# - git init
# - git config user.name "鹿丶羽"
# - git config user.email "panyupy@vip.qq.com"
# - git add .
# - git commit -m "Update docs"
# - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# - rsync -az --delete ./dist/* travis@gz.oidiotlin.com:/var/www/mdzz-web/