language: node_js
node_js: node
branches:
  only:
  - master
addons:
  ssh_known_hosts:
  - 47.99.68.224
before_install:
- openssl aes-256-cbc -K $encrypted_7a49851501cb_key -iv $encrypted_7a49851501cb_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- npm install npm -g
script:
- chmod 600 deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add deploy_rsa
- rm -rf root@47.99.68.224:/home/server/*
# - scp -r ./* root@47.99.68.224:/home/server
# - ssh root@47.99.68.224 'cd /home/server && pm2 stop all && rm -rf ./* && npm install && npm run prd'
# - cd /home/server
# - npm install
# - npm run prd