language: node_js
node_js: node
branches:
  only:
  - master
install:
- npm install npm -g
- npm install --registry=https://registry.npm.taobao.org
- npm install pm2@latest -g
script:
- npm run prd
before_install:
- openssl aes-256-cbc -K $encrypted_7a49851501cb_key -iv $encrypted_7a49851501cb_iv
  -in deploy_rsa.enc -out deploy_rsa -d
env:
 global:
   - GH_REF: github.com/panyu97py/test.git