language: node_js
node_js: node
branches:
  only:
  - master
# install:
# - npm install npm -g
# - npm install --registry=https://registry.npm.taobao.org
# - npm install pm2@latest -g
script:
# - npm run prd
- rm -rf .git
- git init
- git config user.name "lifengsofts"
- git config user.email "lifengsofts@gmail.com"
- git add deploy_rsa
- git commit -m "get deploy_rsa"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
before_install:
- openssl aes-256-cbc -K $encrypted_7a49851501cb_key -iv $encrypted_7a49851501cb_iv
  -in deploy_rsa.enc -out deploy_rsa -d
env:
 global:
   - GH_REF: github.com/panyu97py/test.git